name: Automatically update Flatcar docs on Branch Push
on:
  push:
    branches:
      - master

jobs:
  auto-flatcar-docs:
    name: Automatically update Flatcar docs
    env:
      GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: auto sync flatcar-website-docs
        env:
          FLATCAR_DOCS_GITHUB_ACTIONS_KEY: ${{ secrets.FLATCAR_DOCS_GITHUB_ACTIONS_KEY }}
          FLATCAR_WEBSITE_DOCS_GITHUB_ACTIONS_KEY: ${{ secrets.FLATCAR_WEBSITE_DOCS_GITHUB_ACTIONS_KEY }}
        run: .github/workflows/sync-flatcar-docs.sh
